version: '3.8'

services:
  postgres:
    container_name: llamaws_postgres
    image: postgres:15

    volumes:
      - llamaws_db:/var/lib/postgresql/data

    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: llamaws

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopassword
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: server /data
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - llamaws_minio_data:/data

  adminer:
    container_name: llamaws_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  llamaws_db:
  llamaws_minio_data:
