version: '3.8'

services:
  llamaworkspace:
    container_name: llamaworkspace
    image: llamaworkspace/llamaworkspace:0.0.3-alpha
    ports:
      - 3000:3000
    env_file:
      - ./.env.demo
    command: ['npm', 'run', 'start']
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres

  # networks:
  #   - llamaws_net
  #   - shared_net

  postgres:
    container_name: llamaws_postgres
    image: postgres:15

    volumes:
      - prod_llamaws_db:/var/lib/postgresql/data

    restart: always

    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: llamaws
    # networks:
    #   - llamaws_net

  llamaq:
    container_name: llamaq
    image: llamaworkspace/llamaq:latest
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://llamaq_redis:6379
      - LLAMAQ_ACCESS_KEY=ABC1234
      - NEXTJS_PROCESSOR_URL=http://llamaworkspace:3000
      - NEXTJS_API_ACCESS_KEY=ABC123
    depends_on:
      - redis

    # networks:
    #   - llamaq_net
    #   - shared_net

  redis:
    container_name: llamaq_redis
    image: redis
    restart: always
    volumes:
      - prod_llamaq_redis_data:/data
    # networks:
    #   - llamaq_net

volumes:
  prod_llamaws_db:
  prod_llamaq_redis_data:
# networks:
#   llamaws_net:
#     driver: bridge
#   llamaq_net:
#     driver: bridge
#   shared_net:
#     driver: bridge
